create table if not exists public.alert_signups (
  id bigint generated by default as identity primary key,
  email text not null,
  source text not null,
  event_id text,
  event_title text,
  submitted_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists alert_signups_email_idx on public.alert_signups (email);
create index if not exists alert_signups_source_idx on public.alert_signups (source);
create index if not exists alert_signups_submitted_at_idx on public.alert_signups (submitted_at desc);

alter table public.alert_signups enable row level security;
