create table if not exists public.event_price_snapshots (
  id bigint generated by default as identity primary key,
  event_id text not null,
  event_title text not null,
  provider text not null,
  best_known_price integer not null,
  captured_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists event_price_snapshots_event_id_idx
  on public.event_price_snapshots (event_id, captured_at desc);

create index if not exists event_price_snapshots_provider_idx
  on public.event_price_snapshots (provider);

alter table public.event_price_snapshots enable row level security;
