create table if not exists public.price_drop_candidates (
  id bigint generated by default as identity primary key,
  event_id text not null,
  event_title text not null,
  previous_price integer not null,
  current_price integer not null,
  detected_at timestamptz not null,
  provider text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists price_drop_candidates_event_current_price_key
  on public.price_drop_candidates (event_id, current_price);

create index if not exists price_drop_candidates_detected_at_idx
  on public.price_drop_candidates (detected_at desc);

alter table public.price_drop_candidates enable row level security;
