create table if not exists public.sent_price_drop_alerts (
  id bigint generated by default as identity primary key,
  email text not null,
  event_id text not null,
  event_title text not null,
  previous_price integer not null,
  current_price integer not null,
  provider text not null,
  sent_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists sent_price_drop_alerts_email_event_current_price_key
  on public.sent_price_drop_alerts (email, event_id, current_price);

create index if not exists sent_price_drop_alerts_sent_at_idx
  on public.sent_price_drop_alerts (sent_at desc);

alter table public.sent_price_drop_alerts enable row level security;
